aggrMethod regexes
netdata/dashboard pull request #128
Opened 2020-09-17 15:58 UTC by VLegakis

2020-09-17 16:25 UTC, novykh approved these changes

2020-09-17 18:26 UTC, cakrit requested changes
nice. the only thing I saw missing is "celsius" (lower case C).

2020-09-18 06:42 UTC, VLegakis commented
> nice. the only thing I saw missing is "celsius" (lower case C).

That reminded me the lower cases. I check always against lowercase now. Can you check if it looks ok?

2020-09-18 08:36 UTC, cakrit approved these changes

2020-09-18 08:39 UTC, merged